using Microsoft.AspNetCore.Mvc;
using Quanlicuahang.DTOs.Payment;
using Quanlicuahang.Services;
using Quanlicuahang.Enum;

namespace Quanlicuahang.Controllers
{
    [Route("api/payment-qr")]
    [ApiController]
    public class PaymentQRController : ControllerBase
    {
        private readonly IPaymentService _paymentService;

        public PaymentQRController(IPaymentService paymentService)
        {
            _paymentService = paymentService;
        }

        [HttpPost("create")]
        public async Task<IActionResult> CreateQRPayment([FromBody] PaymentQRCreateDto dto)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            try
            {
                if (!System.Enum.TryParse<PaymentMethod>(dto.PaymentMethod, true, out var paymentMethod))
                {
                    return BadRequest(new { message = $"Phương thức thanh toán không hợp lệ: {dto.PaymentMethod}" });
                }
                var payment = await _paymentService.CreatePaymentForOrderAsync(
                    orderId: dto.OrderId,
                    amount: dto.Amount,
                    paymentMethod: paymentMethod,
                    note: dto.Note ?? $"Thanh toán QR {paymentMethod}",
                    isAutoGenerated: false,
                    paymentStatus: PaymentStatus.Pending
                );

                var response = new PaymentQRResponseDto
                {
                    PaymentId = payment.Id,
                    OrderId = payment.OrderId,
                    Amount = payment.Amount,
                    PaymentMethod = payment.PaymentMethod.ToString(),
                    Status = payment.PaymentStatus.ToString(),
                    ExpiryTime = DateTime.UtcNow.AddMinutes(15), // QR hết hạn sau 15 phút
                    TransactionRef = payment.Code,
                    QRCodeUrl = $"/api/payment-qr/generate-qr/{payment.Id}",
                    PaymentUrl = $"/payment/{payment.Id}"
                };

                return Ok(response);
            }
            catch (System.Exception ex)
            {
                return BadRequest(new { message = ex.Message });
            }
        }

        [HttpGet("status/{paymentId}")]
        public async Task<IActionResult> CheckPaymentStatus([FromRoute] string paymentId)
        {
            try
            {
                var payment = await _paymentService.GetByIdAsync(paymentId);
                if (payment == null)
                    return NotFound(new { message = "Không tìm thấy thanh toán" });

                return Ok(new 
                { 
                    paymentId = payment.Id,
                    status = payment.PaymentStatus,
                    amount = payment.Amount,
                    paymentMethod = payment.PaymentMethod,
                    paymentDate = payment.PaymentDate,
                    note = payment.Note,
                    orderCode = payment.OrderCode,
                    customerName = payment.CustomerName,
                    isCompleted = payment.PaymentStatus == "Completed",
                    message = payment.PaymentStatus == "Completed" ? "Thanh toán đã hoàn thành" : 
                             payment.PaymentStatus == "Pending" ? "Đang chờ thanh toán" :
                             payment.PaymentStatus == "Cancelled" ? "Thanh toán đã hủy" : "Thanh toán thất bại"
                });
            }
            catch (System.Exception ex)
            {
                return BadRequest(new { message = ex.Message });
            }
        }

        [HttpPost("simulate-success/{paymentId}")]
        public async Task<IActionResult> SimulatePaymentSuccess([FromRoute] string paymentId, [FromBody] PaymentCompleteDto? dto)
        {
            try
            {
                var success = await _paymentService.CompletePaymentAsync(paymentId, dto?.Note ?? "Mô phỏng thanh toán QR thành công");
                if (success)
                {
                    var payment = await _paymentService.GetByIdAsync(paymentId);
                    return Ok(new 
                    { 
                        success = true, 
                        message = "Mô phỏng thanh toán thành công",
                        payment = payment
                    });
                }
                else
                {
                    return BadRequest(new { success = false, message = "Không thể mô phỏng thanh toán" });
                }
            }
            catch (System.Exception ex)
            {
                return BadRequest(new { success = false, message = ex.Message });
            }
        }

        [HttpPost("simulate-failed/{paymentId}")]
        public async Task<IActionResult> SimulatePaymentFailed([FromRoute] string paymentId, [FromBody] PaymentCancelDto? dto)
        {
            try
            {
                var success = await _paymentService.CancelPaymentAsync(paymentId, dto?.Reason ?? "Mô phỏng thanh toán QR thất bại");
                if (success)
                {
                    var payment = await _paymentService.GetByIdAsync(paymentId);
                    return Ok(new 
                    { 
                        success = true, 
                        message = "Mô phỏng thanh toán thất bại thành công",
                        payment = payment
                    });
                }
                else
                {
                    return BadRequest(new { success = false, message = "Không thể mô phỏng thanh toán thất bại" });
                }
            }
            catch (System.Exception ex)
            {
                return BadRequest(new { success = false, message = ex.Message });
            }
        }

        [HttpGet("generate-qr/{paymentId}")]
        public async Task<IActionResult> GenerateQRCode([FromRoute] string paymentId)
        {
            try
            {
                var payment = await _paymentService.GetByIdAsync(paymentId);
                if (payment == null)
                    return NotFound(new { message = "Không tìm thấy thanh toán" });

                if (payment.PaymentStatus != "Pending")
                    return BadRequest(new { message = "Chỉ có thể tạo QR code cho thanh toán đang chờ xử lý" });

                var qrData = new
                {
                    paymentId = payment.Id,
                    amount = payment.Amount,
                    orderCode = payment.OrderCode,
                    paymentMethod = payment.PaymentMethod,
                    content = $"Thanh toan don hang {payment.OrderCode}",
                    bankAccount = "1234567890",
                    bankName = "Vietcombank",
                    accountHolder = "CONG TY ABC"
                };

                return Ok(new 
                { 
                    success = true,
                    qrData = qrData,
                    qrString = $"Payment|{payment.Id}|{payment.Amount}|{payment.OrderCode}",
                    message = "Tạo QR code thành công"
                });
            }
            catch (System.Exception ex)
            {
                return BadRequest(new { success = false, message = ex.Message });
            }
        }
    }
}