using Quanlicuahang.Enum;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Quanlicuahang.Models
{
    [Table("Payment")]
    public class Payment : BasePrimary
    {
        [Required, MaxLength(50)]
        public string Code { get; set; } = string.Empty;

        [Required]
        public string OrderId { get; set; } = string.Empty;

        [ForeignKey("OrderId")]
        public virtual Order Order { get; set; } = null!;

        [Required, Column(TypeName = "decimal(10,2)")]
        public decimal Amount { get; set; }

        [Required]
        public PaymentMethod PaymentMethod { get; set; }

        [Required]
        public PaymentStatus PaymentStatus { get; set; } = PaymentStatus.Completed;

        public DateTime PaymentDate { get; set; } = DateTime.UtcNow;

        [MaxLength(200)]
        public string? TransactionRef { get; set; }

        [MaxLength(500)]
        public string? Note { get; set; }

        public bool IsAutoGenerated { get; set; } = false; 
    }
}
