using Microsoft.EntityFrameworkCore;
using Quanlicuahang.DTOs.Payment;
using Quanlicuahang.Enum;
using Quanlicuahang.Helpers;
using Quanlicuahang.Models;
using Quanlicuahang.Repositories;

namespace Quanlicuahang.Services
{
    public interface IPaymentService
    {
        Task<object> GetAllAsync(PaymentSearchDto searchDto);
        Task<PaymentDto?> GetByIdAsync(string id);
        Task<PaymentDto> CreateAsync(PaymentCreateDto dto);
        Task<Payment> CreatePaymentForOrderAsync(string orderId, decimal amount, PaymentMethod paymentMethod, string? note = null, bool isAutoGenerated = false, PaymentStatus paymentStatus = PaymentStatus.Completed);
        Task<bool> UpdateAsync(string id, PaymentUpdateDto dto);
        Task<bool> DeActiveAsync(string id, string? reason = null);
        Task<bool> ActiveAsync(string id, string? reason = null);
        Task<object> GetHistoryByOrderAsync(string orderId);
        Task<object> GetCashflowAsync(PaymentCashflowFilterDto filter);
        Task<string[]> GetMethodsAsync();
        Task<string[]> GetStatusesAsync();
        Task<decimal> GetTotalPaidForOrderAsync(string orderId);
        Task<bool> UpdateOrderStatusBasedOnPaymentAsync(string orderId);
        Task<bool> CompletePaymentAsync(string paymentId, string? note = null);
        Task<bool> CancelPaymentAsync(string paymentId, string? reason = null);
        Task<object> GetPendingPaymentsByOrderAsync(string orderId);
        Task<object> GetAllPendingPaymentsAsync();
    }

    public class PaymentService : IPaymentService
    {
        private readonly IPaymentRepository _paymentRepo;
        private readonly IOrderRepository _orderRepo;
        private readonly IUserRepository _userRepo;
        private readonly IActionLogService _logService;
        private readonly IHttpContextAccessor _httpContext;
        private readonly ITokenHelper _tokenHelper;

        public PaymentService(
            IPaymentRepository paymentRepo,
            IOrderRepository orderRepo,
            IUserRepository userRepo,
            IActionLogService logService,
            IHttpContextAccessor httpContext,
            ITokenHelper tokenHelper)
        {
            _paymentRepo = paymentRepo;
            _orderRepo = orderRepo;
            _userRepo = userRepo;
            _logService = logService;
            _httpContext = httpContext;
            _tokenHelper = tokenHelper;
        }

         public async Task<object> GetAllAsync(PaymentSearchDto searchDto)
        {
            var skip = searchDto.Skip < 0 ? 0 : searchDto.Skip;
            var take = searchDto.Take <= 0 ? 10 : searchDto.Take;

            var query = _paymentRepo.GetAll(true)
                .Include(p => p.Order)
                    .ThenInclude(o => o.Customer)
                .AsQueryable();

            if (searchDto.Where != null)
            {
                var w = searchDto.Where;
                if (!string.IsNullOrWhiteSpace(w.OrderCode))
                {
                    var code = w.OrderCode.Trim().ToLower();
                    query = query.Where(p => p.Order != null && p.Order.Code.ToLower().Contains(code));
                }
                if (!string.IsNullOrWhiteSpace(w.PaymentMethod))
                {
                    if (System.Enum.TryParse<PaymentMethod>(w.PaymentMethod, true, out var method))
                    {
                        query = query.Where(p => p.PaymentMethod == method);
                    }
                }
                if (!string.IsNullOrWhiteSpace(w.CustomerName))
                {
                    var customer = w.CustomerName.Trim().ToLower();
                    query = query.Where(p => p.Order != null && p.Order.Customer != null && p.Order.Customer.Name.ToLower().Contains(customer));
                }
                if (!string.IsNullOrWhiteSpace(w.OrderStatus))
                {
                    if (System.Enum.TryParse<OrderStatus>(w.OrderStatus, true, out var status))
                    {
                        query = query.Where(p => p.Order != null && p.Order.Status == status);
                    }
                }
                if (w.FromDate.HasValue)
                {
                    var from = w.FromDate.Value.Date;
                    query = query.Where(p => p.PaymentDate >= from);
                }
                if (w.ToDate.HasValue)
                {
                    var to = w.ToDate.Value.Date.AddDays(1);
                    query = query.Where(p => p.PaymentDate < to);
                }
                if (w.IsDeleted.HasValue)
                {
                    query = query.Where(p => p.IsDeleted == w.IsDeleted);
                }
            }

            var total = await query.CountAsync();
            var list = await query
                .OrderByDescending(p => p.PaymentDate)
                .Skip(skip)
                .Take(take)
                .Select(p => new
                {
                    p.Id,
                    p.OrderId,
                    OrderCode = p.Order != null ? p.Order.Code : null,
                    CustomerName = p.Order != null && p.Order.Customer != null ? p.Order.Customer.Name : null,
                    p.Amount,
                    p.PaymentMethod,
                    p.PaymentStatus,
                    p.PaymentDate,
                    p.IsDeleted,
                    p.CreatedAt,
                    p.UpdatedAt,
                    p.CreatedBy,
                    p.Note,
                    OrderStatus = p.Order != null ? p.Order.Status.ToString() : null
                })
                .ToListAsync();

            var userIds = list.Select(x => x.CreatedBy).Where(id => !string.IsNullOrEmpty(id)).Distinct().ToList();
            var userMap = new Dictionary<string, string>();
            if (userIds.Any())
            {
                var users = await _userRepo.GetAll(true)
                    .Where(u => userIds.Contains(u.Id))
                    .Select(u => new { u.Id, Name = u.FullName ?? u.Username })
                    .ToListAsync();
                userMap = users.ToDictionary(u => u.Id, u => u.Name);
            }

            var data = list.Select(p => new PaymentDto
            {
                Id = p.Id,
                OrderId = p.OrderId,
                OrderCode = p.OrderCode,
                CustomerName = p.CustomerName,
                Amount = p.Amount,
                PaymentMethod = p.PaymentMethod.ToString(),
                PaymentStatus = p.PaymentStatus.ToString(),
                PaymentDate = p.PaymentDate,
                IsDeleted = p.IsDeleted,
                CreatedAt = p.CreatedAt,
                UpdatedAt = p.UpdatedAt,
                OperatorName = p.CreatedBy != null && userMap.ContainsKey(p.CreatedBy) ? userMap[p.CreatedBy] : null,
                OrderStatus = p.OrderStatus,
                Note = p.Note,
                isCanView = true,
                isCanCreate = true,
                isCanEdit = !p.IsDeleted,
                isCanDeActive = !p.IsDeleted,
                isCanActive = p.IsDeleted
            }).ToList();

            return new { data, total };
        }
       
        public async Task<PaymentDto?> GetByIdAsync(string id)
        {
            var raw = await _paymentRepo.GetAll(true)
                .Include(p => p.Order)
                    .ThenInclude(o => o.Customer)
                .Where(p => p.Id == id)
                .Select(p => new
                {
                    p.Id,
                    p.OrderId,
                    OrderCode = p.Order != null ? p.Order.Code : null,
                    CustomerName = p.Order != null && p.Order.Customer != null ? p.Order.Customer.Name : null,
                    p.Amount,
                    p.PaymentMethod,
                    p.PaymentStatus,
                    p.PaymentDate,
                    p.IsDeleted,
                    p.CreatedAt,
                    p.UpdatedAt,
                    p.CreatedBy,
                    p.Note,
                    OrderStatus = p.Order != null ? p.Order.Status.ToString() : null
                })
                .FirstOrDefaultAsync();

            if (raw == null) return null;

            string? opName = null;
            if (!string.IsNullOrEmpty(raw.CreatedBy))
            {
                var user = await _userRepo.GetByIdAsync(raw.CreatedBy);
                opName = user?.FullName ?? user?.Username;
            }

            return new PaymentDto
            {
                Id = raw.Id,
                OrderId = raw.OrderId,
                OrderCode = raw.OrderCode,
                CustomerName = raw.CustomerName,
                Amount = raw.Amount,
                PaymentMethod = raw.PaymentMethod.ToString(),
                PaymentStatus = raw.PaymentStatus.ToString(),
                PaymentDate = raw.PaymentDate,
                IsDeleted = raw.IsDeleted,
                CreatedAt = raw.CreatedAt,
                UpdatedAt = raw.UpdatedAt,
                OperatorName = opName,
                OrderStatus = raw.OrderStatus,
                Note = raw.Note
            };
        }

        public async Task<PaymentDto> CreateAsync(PaymentCreateDto dto)
        {
            if (dto.Amount <= 0)
                throw new System.Exception("Số tiền thanh toán phải lớn hơn 0");

            Order? order = null;

            if (!string.IsNullOrWhiteSpace(dto.OrderId))
                order = await _orderRepo.GetByIdAsync(dto.OrderId);

            else if (!string.IsNullOrWhiteSpace(dto.OrderCode))
            {
                var code = dto.OrderCode.Trim().ToLower();
                order = await _orderRepo.GetAll(false)
                    .Where(o => o.Code.ToLower() == code)
                    .FirstOrDefaultAsync();
            }

            if (order == null || order.IsDeleted)
                throw new System.Exception("Đơn hàng không tồn tại hoặc đã bị xóa");

            if (!System.Enum.TryParse<PaymentMethod>(dto.PaymentMethod, true, out var method))
                throw new System.Exception("Phương thức thanh toán không hợp lệ (Cash | BankTransfer | Card | Momo | VnPay | Zalo)");

            var userId = await _tokenHelper.GetUserIdFromTokenAsync();
            if (userId == null) throw new UnauthorizedAccessException();

            var ip = _httpContext.HttpContext?.Connection?.RemoteIpAddress?.ToString();
            var agent = _httpContext.HttpContext?.Request.Headers["User-Agent"].ToString();

            var net = order.TotalAmount - order.DiscountAmount;
            var paid = await _paymentRepo.GetTotalPaidByOrderAsync(order.Id);

            if (paid + dto.Amount > net)
                throw new System.Exception($"Thanh toán vượt quá giá trị đơn hàng. Số dư còn lại: {net - paid}");

            var payment = new Payment
            {
                Id = Guid.NewGuid().ToString(),
                OrderId = order.Id,
                Amount = dto.Amount,
                PaymentMethod = method,
                PaymentStatus = PaymentStatus.Completed,
                PaymentDate = dto.PaymentDate ?? DateTime.UtcNow,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow,
                CreatedBy = userId,
                UpdatedBy = userId,
                Note = dto.Note
            };

            await _paymentRepo.AddAsync(payment);
            await _paymentRepo.SaveChangesAsync();

            var newPaid = paid + dto.Amount;
            UpdateOrderStatus(order, newPaid, net, userId);
            _orderRepo.Update(order);
            await _orderRepo.SaveChangesAsync();

            await _logService.LogAsync(
                code: Guid.NewGuid().ToString(),
                action: "Create",
                entityType: "Payments",
                entityId: payment.Id,
                description: $"Tạo thanh toán {method} - {dto.Amount}",
                oldValue: null,
                newValue: payment,
                userId: userId,
                ip: ip,
                userAgent: agent
            );

            return (await GetByIdAsync(payment.Id))!;
        }

        public async Task<bool> UpdateAsync(string id, PaymentUpdateDto dto)
        {
            var payment = await _paymentRepo.GetByIdAsync(id);
            if (payment == null || payment.IsDeleted) return false;

            if (payment.PaymentStatus != PaymentStatus.Pending)
                throw new System.Exception("Chỉ có thể cập nhật thanh toán đang ở trạng thái Pending");

            var order = await _orderRepo.GetByIdAsync(payment.OrderId);
            if (order == null || order.IsDeleted) return false;

            if (dto.Amount <= 0)
                throw new System.Exception("Số tiền thanh toán phải lớn hơn 0");

            if (!System.Enum.TryParse<PaymentMethod>(dto.PaymentMethod, true, out var method))
                method = payment.PaymentMethod;

            PaymentStatus status = payment.PaymentStatus;
            if (!string.IsNullOrWhiteSpace(dto.PaymentStatus))
            {
                if (!System.Enum.TryParse<PaymentStatus>(dto.PaymentStatus, true, out status))
                    status = payment.PaymentStatus;
            }

            var userId = await _tokenHelper.GetUserIdFromTokenAsync();

            var net = order.TotalAmount - order.DiscountAmount;
            var paidExcluding = await _paymentRepo.GetTotalPaidByOrderExcludingAsync(order.Id, payment.Id);

            if (paidExcluding + dto.Amount > net)
                throw new System.Exception($"Tổng thanh toán vượt quá số tiền cần thanh toán");

            var before = new
            {
                payment.Amount,
                payment.PaymentMethod,
                payment.PaymentStatus,
                payment.PaymentDate,
                payment.Note
            };

            payment.Amount = dto.Amount;
            payment.PaymentMethod = method;
            payment.PaymentStatus = status;
            payment.PaymentDate = dto.PaymentDate ?? payment.PaymentDate;
            payment.Note = dto.Note;
            payment.UpdatedBy = userId ?? payment.UpdatedBy;
            payment.UpdatedAt = DateTime.UtcNow;

            _paymentRepo.Update(payment);
            await _paymentRepo.SaveChangesAsync();

            var newPaid = await _paymentRepo.GetTotalPaidByOrderAsync(order.Id);
            UpdateOrderStatus(order, newPaid, net, userId);
            _orderRepo.Update(order);
            await _orderRepo.SaveChangesAsync();

            await _logService.LogAsync(
                code: Guid.NewGuid().ToString(),
                action: "Update",
                entityType: "Payments",
                entityId: payment.Id,
                description: $"Cập nhật thanh toán {payment.Id}",
                oldValue: before,
                newValue: payment,
                userId: userId,
                ip: _httpContext.HttpContext?.Connection?.RemoteIpAddress?.ToString(),
                userAgent: _httpContext.HttpContext?.Request.Headers["User-Agent"].ToString()
            );

            return true;
        }


        public async Task<bool> DeActiveAsync(string id, string? reason = null)
        {
            var payment = await _paymentRepo.GetByIdAsync(id);
            if (payment == null) return false;

            payment.IsDeleted = true;
            payment.UpdatedAt = DateTime.UtcNow;

            var userId = await _tokenHelper.GetUserIdFromTokenAsync();

            _paymentRepo.Update(payment);
            await _paymentRepo.SaveChangesAsync();

            var order = await _orderRepo.GetByIdAsync(payment.OrderId);

            if (order != null && !order.IsDeleted)
            {
                var net = order.TotalAmount - order.DiscountAmount;
                var paid = await _paymentRepo.GetTotalPaidByOrderAsync(order.Id);

                UpdateOrderStatus(order, paid, net, userId);
                _orderRepo.Update(order);
                await _orderRepo.SaveChangesAsync();
            }

            await _logService.LogAsync(
                code: Guid.NewGuid().ToString(),
                action: "DeActive",
                entityType: "Payments",
                entityId: payment.Id,
                description: $"Vô hiệu hóa thanh toán {payment.Id}",
                oldValue: null,
                newValue: new { payment.IsDeleted, reason },
                userId: userId,
                ip: _httpContext.HttpContext?.Connection?.RemoteIpAddress?.ToString(),
                userAgent: _httpContext.HttpContext?.Request.Headers["User-Agent"].ToString()
            );

            return true;
        }

        public async Task<bool> ActiveAsync(string id, string? reason = null)
        {
            var payment = await _paymentRepo.GetByIdAsync(id);
            if (payment == null) return false;

            payment.IsDeleted = false;
            payment.UpdatedAt = DateTime.UtcNow;

            var userId = await _tokenHelper.GetUserIdFromTokenAsync();

            _paymentRepo.Update(payment);
            await _paymentRepo.SaveChangesAsync();

            var order = await _orderRepo.GetByIdAsync(payment.OrderId);

            if (order != null && !order.IsDeleted)
            {
                var net = order.TotalAmount - order.DiscountAmount;
                var paid = await _paymentRepo.GetTotalPaidByOrderAsync(order.Id);

                UpdateOrderStatus(order, paid, net, userId);
                _orderRepo.Update(order);
                await _orderRepo.SaveChangesAsync();
            }

            await _logService.LogAsync(
                code: Guid.NewGuid().ToString(),
                action: "Active",
                entityType: "Payments",
                entityId: payment.Id,
                description: $"Kích hoạt lại thanh toán {payment.Id}",
                oldValue: null,
                newValue: new { payment.IsDeleted, reason },
                userId: userId,
                ip: _httpContext.HttpContext?.Connection?.RemoteIpAddress?.ToString(),
                userAgent: _httpContext.HttpContext?.Request.Headers["User-Agent"].ToString()
            );

            return true;
        }
        public async Task<object> GetHistoryByOrderAsync(string orderId)
        {
            var list = await _paymentRepo.GetAll(true)
                .Include(p => p.Order)
                    .ThenInclude(o => o.Customer)
                .Where(p => p.OrderId == orderId)
                .OrderByDescending(p => p.PaymentDate)
                .ToListAsync();

            var data = list.Select(p => new PaymentDto
            {
                Id = p.Id,
                OrderId = p.OrderId,
                OrderCode = p.Order.Code,
                CustomerName = p.Order.Customer?.Name,
                Amount = p.Amount,
                PaymentMethod = p.PaymentMethod.ToString(),
                PaymentStatus = p.PaymentStatus.ToString(),
                PaymentDate = p.PaymentDate,
                IsDeleted = p.IsDeleted,
                CreatedAt = p.CreatedAt,
                UpdatedAt = p.UpdatedAt,
                Note = p.Note,
                OrderStatus = p.Order.Status.ToString()
            });

            return new { data, total = data.Count() };
        }

        public async Task<object> GetCashflowAsync(PaymentCashflowFilterDto filter)
        {
            return await _paymentRepo.GetCashflowAsync(
                filter.FromDate,
                filter.ToDate,
                filter.Skip,
                filter.Take
            );
        }

        public Task<string[]> GetMethodsAsync()
        {
            return Task.FromResult(System.Enum.GetNames(typeof(PaymentMethod)));
        }

        public Task<string[]> GetStatusesAsync()
        {
            return Task.FromResult(System.Enum.GetNames(typeof(PaymentStatus)));
        }


        public async Task<Payment> CreatePaymentForOrderAsync(string orderId, decimal amount, PaymentMethod paymentMethod, string? note = null, bool isAutoGenerated = false, PaymentStatus paymentStatus = PaymentStatus.Completed)
        {
            if (amount <= 0)
                throw new System.Exception("Số tiền thanh toán phải lớn hơn 0");

            var order = await _orderRepo.GetByIdAsync(orderId);
            if (order == null || order.IsDeleted)
                throw new System.Exception("Đơn hàng không tồn tại hoặc đã bị xóa");

            var userId = await _tokenHelper.GetUserIdFromTokenAsync();

            var payment = new Payment
            {
                Id = Guid.NewGuid().ToString(),
                Code = GeneratePaymentCode(),
                OrderId = orderId,
                Amount = amount,
                PaymentMethod = paymentMethod,
                PaymentStatus = paymentStatus,
                PaymentDate = DateTime.UtcNow,
                IsAutoGenerated = isAutoGenerated,
                Note = note ?? (isAutoGenerated ? "Thanh toán tự động khi tạo đơn hàng" : null),
                CreatedBy = userId ?? "system",
                UpdatedBy = userId ?? "system",
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow
            };

            await _paymentRepo.AddAsync(payment);
            return payment;
        }

        public async Task<decimal> GetTotalPaidForOrderAsync(string orderId)
        {
            return await _paymentRepo.GetAll(false)
                .Where(p => p.OrderId == orderId && p.PaymentStatus == PaymentStatus.Completed && !p.IsDeleted)
                .SumAsync(p => p.Amount);
        }

        public async Task<bool> CompletePaymentAsync(string paymentId, string? note = null)
        {
            var payment = await _paymentRepo.GetByIdAsync(paymentId);
            if (payment == null || payment.IsDeleted)
                throw new System.Exception("Thanh toán không tồn tại hoặc đã bị xóa");

            if (payment.PaymentStatus != PaymentStatus.Pending)
                throw new System.Exception($"Chỉ có thể hoàn thành thanh toán đang ở trạng thái Pending. Trạng thái hiện tại: {payment.PaymentStatus}");

            var userId = await _tokenHelper.GetUserIdFromTokenAsync();
            
            payment.PaymentStatus = PaymentStatus.Completed;
            payment.PaymentDate = DateTime.UtcNow; 
            if (!string.IsNullOrWhiteSpace(note))
            {
                payment.Note = string.IsNullOrWhiteSpace(payment.Note) ? note : $"{payment.Note}\n{note}";
            }
            payment.UpdatedBy = userId ?? payment.UpdatedBy;
            payment.UpdatedAt = DateTime.UtcNow;

            _paymentRepo.Update(payment);
            await _paymentRepo.SaveChangesAsync();

            await UpdateOrderStatusBasedOnPaymentAsync(payment.OrderId);

            await _logService.LogAsync(
                code: Guid.NewGuid().ToString(),
                action: "CompletePayment",
                entityType: "Payments",
                entityId: payment.Id,
                description: $"Hoàn thành thanh toán {payment.PaymentMethod} - {payment.Amount:C}",
                oldValue: new { PaymentStatus = PaymentStatus.Pending },
                newValue: new { PaymentStatus = PaymentStatus.Completed, payment.PaymentDate },
                userId: userId,
                ip: _httpContext.HttpContext?.Connection?.RemoteIpAddress?.ToString(),
                userAgent: _httpContext.HttpContext?.Request.Headers["User-Agent"].ToString()
            );

            return true;
        }

        public async Task<bool> CancelPaymentAsync(string paymentId, string? reason = null)
        {
            var payment = await _paymentRepo.GetByIdAsync(paymentId);
            if (payment == null || payment.IsDeleted)
                throw new System.Exception("Thanh toán không tồn tại hoặc đã bị xóa");

            if (payment.PaymentStatus != PaymentStatus.Pending)
                throw new System.Exception($"Chỉ có thể hủy thanh toán đang ở trạng thái Pending. Trạng thái hiện tại: {payment.PaymentStatus}");

            var userId = await _tokenHelper.GetUserIdFromTokenAsync();
            
            payment.PaymentStatus = PaymentStatus.Cancelled;
            if (!string.IsNullOrWhiteSpace(reason))
            {
                payment.Note = string.IsNullOrWhiteSpace(payment.Note) ? $"Hủy: {reason}" : $"{payment.Note}\nHủy: {reason}";
            }
            payment.UpdatedBy = userId ?? payment.UpdatedBy;
            payment.UpdatedAt = DateTime.UtcNow;

            _paymentRepo.Update(payment);
            await _paymentRepo.SaveChangesAsync();

            await UpdateOrderStatusBasedOnPaymentAsync(payment.OrderId);

            await _logService.LogAsync(
                code: Guid.NewGuid().ToString(),
                action: "CancelPayment",
                entityType: "Payments",
                entityId: payment.Id,
                description: $"Hủy thanh toán {payment.PaymentMethod} - {payment.Amount:C}. Lý do: {reason}",
                oldValue: new { PaymentStatus = PaymentStatus.Pending },
                newValue: new { PaymentStatus = PaymentStatus.Cancelled, Reason = reason },
                userId: userId,
                ip: _httpContext.HttpContext?.Connection?.RemoteIpAddress?.ToString(),
                userAgent: _httpContext.HttpContext?.Request.Headers["User-Agent"].ToString()
            );

            return true;
        }

        public async Task<bool> UpdateOrderStatusBasedOnPaymentAsync(string orderId)
        {
            var order = await _orderRepo.GetByIdAsync(orderId);
            if (order == null || order.IsDeleted) return false;

            var totalPaid = await GetTotalPaidForOrderAsync(orderId);
            var netAmount = order.TotalAmount - order.DiscountAmount;

            var userId = await _tokenHelper.GetUserIdFromTokenAsync();

            order.PaidAmount = totalPaid;
            
            if (totalPaid <= 0)
                order.Status = OrderStatus.Pending;
            else if (totalPaid >= netAmount)
                order.Status = OrderStatus.Paid;
            else
                order.Status = OrderStatus.Confirmed; 

            order.UpdatedBy = userId ?? order.UpdatedBy;
            order.UpdatedAt = DateTime.UtcNow;

            _orderRepo.Update(order);
            await _orderRepo.SaveChangesAsync();

            return true;
        }


        public async Task<object> GetPendingPaymentsByOrderAsync(string orderId)
        {
            var pendingPayments = await _paymentRepo.GetAll(false)
                .Include(p => p.Order)
                    .ThenInclude(o => o.Customer)
                .Where(p => p.OrderId == orderId && p.PaymentStatus == PaymentStatus.Pending && !p.IsDeleted)
                .OrderByDescending(p => p.CreatedAt)
                .Select(p => new PaymentDto
                {
                    Id = p.Id,
                    OrderId = p.OrderId,
                    OrderCode = p.Order.Code,
                    CustomerName = p.Order.Customer != null ? p.Order.Customer.Name : null,
                    Amount = p.Amount,
                    PaymentMethod = p.PaymentMethod.ToString(),
                    PaymentStatus = p.PaymentStatus.ToString(),
                    PaymentDate = p.PaymentDate,
                    CreatedAt = p.CreatedAt,
                    UpdatedAt = p.UpdatedAt,
                    Note = p.Note,
                    OrderStatus = p.Order.Status.ToString(),
                    isCanView = true,
                    isCanEdit = true,
                    isCanDeActive = false,
                    isCanActive = false
                })
                .ToListAsync();

            return new { data = pendingPayments, total = pendingPayments.Count };
        }


        public async Task<object> GetAllPendingPaymentsAsync()
        {
            var allPendingPayments = await _paymentRepo.GetAll(false)
                .Include(p => p.Order)
                    .ThenInclude(o => o.Customer)
                .Where(p => p.PaymentStatus == PaymentStatus.Pending && !p.IsDeleted)
                .OrderByDescending(p => p.CreatedAt)
                .Select(p => new PaymentDto
                {
                    Id = p.Id,
                    OrderId = p.OrderId,
                    OrderCode = p.Order.Code,
                    CustomerName = p.Order.Customer != null ? p.Order.Customer.Name : null,
                    Amount = p.Amount,
                    PaymentMethod = p.PaymentMethod.ToString(),
                    PaymentStatus = p.PaymentStatus.ToString(),
                    PaymentDate = p.PaymentDate,
                    CreatedAt = p.CreatedAt,
                    UpdatedAt = p.UpdatedAt,
                    Note = p.Note,
                    OrderStatus = p.Order.Status.ToString(),
                    isCanView = true,
                    isCanEdit = true,
                    isCanDeActive = false,
                    isCanActive = false
                })
                .ToListAsync();

            return new { data = allPendingPayments, total = allPendingPayments.Count };
        }

        private static string GeneratePaymentCode()
        {
            var timestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
            var randomPart = Guid.NewGuid().ToString("N").Substring(0, 6);
            return $"pay-{timestamp}-{randomPart}";
        }

        private static void UpdateOrderStatus(Order order, decimal paid, decimal netAmount, string? userId)
        {
            if (paid <= 0)
                order.Status = OrderStatus.Pending;
            else if (paid >= netAmount)
                order.Status = OrderStatus.Paid;
            else
                order.Status = OrderStatus.Confirmed;

            order.PaidAmount = paid;
            order.UpdatedAt = DateTime.UtcNow;
            order.UpdatedBy = userId ?? order.UpdatedBy;
        }
    }
}